accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
]

articles/urls.py
from django.urls import path
from django.conf.urls import include,url
from . import views

app_name = 'articles'

urlpatterns = [
  
  #path('',views.articles_list),
  #path('',views.article_detail),
  url(r'^$',views.articles_list,name="list"),

  #url to create a new article
  url(r'^create/$',views.article_create,name="create"),

  #a named capturing group
  #To create a named capturing group we have to say ?P
  #In angular brackets we have to write the name of the thing we want to capture
  #\w:any type of letter,underscore
  #^:start
  # $:end
  # - means: - can also be included in url
  # + means: that thing before it can be of any length
  url(r'^(?P<slug>[\w-]+)/$',views.articles_details,name="detail"),

]

blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    url(r'^$',article_views.articles_list,name="home"),
]

urlpatterns +=staticfiles_urlpatterns()
urlpatterns +=static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
# Model is always represented by class
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug  = models.SlugField()
    body  = models.TextField()
    #auto_add_now field will automatically assign a current date to the post we create
    date  = models.DateTimeField(auto_now_add=True)
    #first parameter-default image
    #second parameter is saying that it is not necessary
    thumb = models.ImageField(default='default.png', blank=True)
    #add in author later
    #default=none specify that there is always one user associated with an article
    author = models.ForeignKey(User,on_delete=models.CASCADE,default=None)

    def __str__(self):
        return self.title

    #takes self as a input which is the instance of the article
    def snippet(self):
        #so we want to cut down the body.we want to make it 50 characters long.
        return self.body[:50]+'...'
    

articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        #import model
        model = models.Article
        #fields that we want to output.
        fields = ['title', 'body', 'slug', 'thumb',]

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout

def signup_view(request):
    '''
    If the request is post then we will take the data that we've 
    got from the form and we want to somehow validate it and the way we do that
    is by following:
    '''
    if request.method == 'POST':
        '''
        What this instance is doing is essentially kind of valid in that data 
        for us.If this data is okay(like user is already exists or not,password in 
        long enough or not etc..).That's going to return us a instance of form 
        that is either valid or invalid.If it is valid save that form to database.
        '''
        form = UserCreationForm(request.POST)
        if form.is_valid():
            #log the user in
            user = form.save()
            #after getting user we will try to login that user
            login(request, user)
            #redirect the user to articles list page
            return redirect('articles:list')
    #if the request is get then create a blank instance of user creation form.
    else:
        #create a new instance of the form
        form = UserCreationForm()
    #send that form to template
    return render(request, 'accounts/signup.html',{'form':form})

def login_view(request):
    '''
    same as the signup view,in the login we can also have get request or post request
    if the request is post
    '''
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            #log the user in
            #first of all we need to get what the user is,who's trying to log in 
            user = form.get_user()
            #after getting user we will try to login that user
            login(request, user)

            #for redirecting  
            if 'next' in request.POST:
                    return redirect(request.POST.get('next'))
            else:
               return redirect('articles:list')
            #redirect the user to articles list page
            return redirect('articles:list')
    else:
        #this will be get request.When user clicks on login link or he will go to /accounts/login/ 
        #we will send them a login form to the template and render that form in the browser
        #create a new instance of the form
        form = AuthenticationForm()
    return render(request, 'accounts/login.html',{'form':form})

def logout_view(request):
    if request.method == 'POST':
        #we don't need to pass the current user becuase he is already logged in as a user.
        #it will logout the current user
        logout(request)
        #once the user is logged out we'll do some kind of redirect.
        return redirect('articles:list')

        
   

articles/views.py
from django.shortcuts import render,redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms

'''
Takes in the request object.
All we are going to do in this function is we will render a template
     to the user which is going to show a list of articles.
First parameter in render is always the request object and the second parameter is
     the template we want to render and third optional is the directory
'''
def articles_list(request):
    #Retrieve all articles from database and sort them according to date
    articles = Article.objects.all().order_by('date')
    return render(request, 'articles/articles_list.html',{'articles':articles})

def articles_details(request, slug):
    #return HttpResponse(slug)
    article = Article.objects.get(slug=slug)
    return render(request,'articles/article_detail.html',{'article':article})

#if the user is not already logged in than send the user to login page first
@login_required(login_url="/accounts/login/")
def article_create(request):
    #if the request is post then retrieve the data,which user has entered in the form 
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            # save article to db
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/article_create.html', { 'form': form })

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %} {% block content %}
<h1>Login</h1>
<br>
<br>
<!--site-form is for stying purposes -->
<form class="site-form" action="/accounts/login/" method="post">
    {% csrf_token %}
    <!-- output all of fields which comes baked with django inbuilt form -->
    {{ form }} 
    
    <!-- input field is hidden.So a user can't see it-->
    {% if request.GET.next %}
    <input type="hidden" name="next" value="{{ request.GET.next }}" /> {% endif %}

    <input type="submit" value="Login">
</form>

<br><br>
<p>Not got an account? <a href="{% url 'accounts:signup' %}">Sign Up</a></p>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %} {% block content %}
<h1>Signup</h1>
<br>
<br>
<!--site-form is for stying purposes -->
<form class="site-form" action="/accounts/signup/" method="post">
    {% csrf_token %}
    <!-- output all of fields which comes baked with django inbuilt form -->
    {{ form }}

    <input type="submit" value="Signup">
</form>
{% endblock %}

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %} {% block content %}
<div class="create-article">
    <h2>Create an Awesome New Article</h2>
    <form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %} {{ form }}
        <input type="submit" value="Create">
    </form>
</div>
<script src="/static/slugify.js"></script>
{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %} {% block content%}
<br>
<br>
<div class="article-detail">
    <div class="article">
        <img src="{{ article.thumb.url }}" />
        <h2>{{ article.title }}</h2>
        <p>{{ article.body }}</p>
        <p>{{ article.date }}</p>
    </div>
</div>

{% endblock %}

articles/templates/articles/articles_list.html
{% extends 'base_layout.html' %} {% block content%}
<h1>Articles List</h1>
<br>
<br>
<div class="articles">
    {% for article in articles %}
    <div class="article">
        <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a></h2>
        <p>{{ article.snippet }}</p>
        <p>{{ article.date }}</p>
        <p class="author">added by {{article.author.username}}</p>
        <br>
    </div>
    {% endfor %} {% endblock %}

templates/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Djangonauts</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>

<body>
    <header class="wrapper">
        <h1>
            <a href="{% url 'home' %}"><img src="{% static 'logo.png' %}" alt="djangonautic" /></a>
        </h1>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                <li>
                    <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit">Logout</button>
                    </form>
                </li>
                <li><a href="{% url 'articles:create' %}" class="highlight">New Article</a></li>
                {% else %}
                <li><a href="{% url 'accounts:login' %}">Login</a></li>
                <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <div class="wrapper">
        {% block content %} {% endblock %}
    </div>
</body>

</html>